### ISSUE TITLE
Developer/Lab 3/Consider pre-populating local Maven repo for image used in Eclipse Che

### ISSUE THREAD

**Issue by mbogoevici** [RedHatWorkshops/dayinthelife-integration#162] opened 2018-10-27 15:24 UTC
During lab execution, Maven steps take significant times to complete due to Maven having to download all dependencies from scratch on each new Che instances. This is likely to put the strain on the cluster due to simultaneous downloads and also creates an idle time for the user as they run the lab - which could be easily avoided.

**Comment by sigreen** [comment] 2018-10-30 12:54
Duplicate of #64

**Closed by sigreen** 2018-10-30 12:54 UTC
