### ISSUE TITLE
Create Gogs users fails, HTTP 302

### ISSUE THREAD

**Issue by vap0rtranz** [RedHatWorkshops/dayinthelife-integration#305] opened 2019-03-23 17:33 UTC
Error from playbook task below.  Looks similar to issue #285 but that is closed.  This error is from V2 branch.

Retrying the Gogs URL worked after letting Ansible finish install, so two ideas: the task should be delayed to later in the playbook to allow Gogs Pods to come up?  and/or SSO broken for these accounts that the task is trying to login with?  

```
failed: [localhost] (item=user0) => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "text/plain; charset=utf-8", "date": "Sat, 23 Mar 2019 17:20:23 GMT", "item": "user0", "location": "http://gogs.apps.dil-testing-0345.openshiftworkshop.com/user/login", "msg": "Status code was 302 and not [200]: HTTP Error 302: Found", "redirected": false, "set_cookie": "lang=en-US; Path=/; Max-Age=2147483647, i_like_gogits=4ada29c3970e50c6; Path=/; HttpOnly, _csrf=y_PZ8rq80pLy6RaTg8kgtc3BaeY6MTU1MzM2MTYyMzUwOTkwMTA0OQ%3D%3D; Path=/; Expires=Sun, 24 Mar 2019 17:20:23 GMT; HttpOnly, 50f55086d25523a6f277aa8a542368c8=62e15293cde0a3e554c2f0fa95c0db85; path=/; HttpOnly", "status": 302, "url": "http://gogs.apps.dil-testing-0345.openshiftworkshop.com/user/sign_up"}
```

**Comment by sigreen** [comment] 2019-04-08 12:37
Unable to reproduce the problem after running the V2 scripts that were migrated to Master.  Closing this issue.

**Closed by sigreen** 2019-04-08 12:37 UTC
